name: paramak-dev-environment

dependencies:
  - openmc<=0.15.0=dagmc*
  - cadquery<=2.5.2
  - gmsh
  - python-gmsh
  - numpy
  - pytest
  - pip
  - mpmath
  - sympy
  - cad_to_dagmc
  - sphinx
  - pydata-sphinx-theme
  - pip:
    - sphinx_autodoc_typehints
    - openmc_data_downloader
    - sphinxcadquery
