name: docs-environment

channels:
  - conda-forge
  - cadquery

dependencies:
  - cadquery=2.1
  - plotly<=5.3.0
  - scipy<=1.6.2
  - numpy>=1.9
  - matplotlib<=3.4.2
  - pillow<=8.3.1
  - sympy<=1.8.0
  - defusedxml<=0.7.1
  - plasmaboundaries
  - sphinx-autodoc-typehints<=1.12.0
  - pip<=21.2.4
  - pip:
    - sphinxcadquery
    - jupyter-cadquery
