name: docs-environment

channels:
  - conda-forge
  - cadquery

dependencies:
  - cadquery=2.1
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - pillow
  - sympy
  - defusedxml
  - plasmaboundaries
  - sphinx-autodoc-typehints
  - pip:
    - sphinxcadquery
    - jupyter-cadquery
